import { z } from "zod";
export declare const schemeTypeEnum: any;
export declare const coverageLevelEnum: any;
export declare const schemeStatusEnum: any;
export declare const benefitTypeEnum: any;
export declare const limitTypeEnum: any;
export declare const waitingPeriodTypeEnum: any;
export declare const insuranceSchemes: any;
export declare const schemeBenefits: any;
export declare const schemeNetworks: any;
export declare const schemeRiders: any;
export declare const schemePricing: any;
export declare const schemeVersions: any;
export declare const schemeEligibilityRules: any;
export declare const insertInsuranceSchemeSchema: any;
export declare const insertSchemeBenefitSchema: any;
export declare const insertSchemeNetworkSchema: any;
export declare const insertSchemeRiderSchema: any;
export declare const insertSchemePricingSchema: any;
export declare const insertSchemeVersionSchema: any;
export declare const insertSchemeEligibilityRuleSchema: any;
export type InsuranceScheme = typeof insuranceSchemes.$inferSelect;
export type SchemeBenefit = typeof schemeBenefits.$inferSelect;
export type SchemeNetwork = typeof schemeNetworks.$inferSelect;
export type SchemeRider = typeof schemeRiders.$inferSelect;
export type SchemePricing = typeof schemePricing.$inferSelect;
export type SchemeVersion = typeof schemeVersions.$inferSelect;
export type SchemeEligibilityRule = typeof schemeEligibilityRules.$inferSelect;
export type InsertInsuranceScheme = z.infer<typeof insertInsuranceSchemeSchema>;
export type InsertSchemeBenefit = z.infer<typeof insertSchemeBenefitSchema>;
export type InsertSchemeNetwork = z.infer<typeof insertSchemeNetworkSchema>;
export type InsertSchemeRider = z.infer<typeof insertSchemeRiderSchema>;
export type InsertSchemePricing = z.infer<typeof insertSchemePricingSchema>;
export type InsertSchemeVersion = z.infer<typeof insertSchemeVersionSchema>;
export type InsertSchemeEligibilityRule = z.infer<typeof insertSchemeEligibilityRuleSchema>;
