import {
  pgTable,
  text,
  serial,
  integer,
  boolean,
  date,
  timestamp,
  real,
  pgEnum,
  uuid,
  varchar,
  decimal,
  jsonb,
  index
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Import shared enums and tables
import {
  memberTypeEnum,
  dependentTypeEnum,
  periodStatusEnum,
  periodTypeEnum,
  benefitCategoryEnum,
  institutionTypeEnum,
  personnelTypeEnum,
  approvalStatusEnum,
  claimStatusEnum,
  premiumRateTypeEnum,
  pricingMethodologyEnum,
  riskAdjustmentTierEnum,
  inflationCategoryEnum,
  networkTierEnum,
  contractStatusEnum,
  tariffStatusEnum,
  reimbursementModelEnum,
  genderEnum,
  maritalStatusEnum,
  membershipStatusEnum,
  clientTypeEnum,
  billingFrequencyEnum,
  lifeEventTypeEnum,
  documentTypeEnum,
  communicationTypeEnum,
  communicationChannelEnum,
  deliveryStatusEnum,
  consentTypeEnum,
  auditActionEnum,
  auditEntityTypeEnum,
  benefits,
  premiumRates,
  periods,
  schemeBenefits,
  insuranceSchemes
// @ts-ignore: Shared schema import path resolution
} from "../../../shared/schemas/schema.js";

// Re-export tables and enums that are used externally
export {
  benefitCategoryEnum,
  memberTypeEnum,
  dependentTypeEnum,
  periodStatusEnum,
  periodTypeEnum,
  benefits,
  premiumRates,
  periods,
  schemeBenefits,
  insuranceSchemes
};

// Companies table
export const companies = pgTable("companies", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  registrationNumber: text("registration_number").notNull().unique(),
  contactPerson: text("contact_person").notNull(),
  contactEmail: text("contact_email").notNull(),
  contactPhone: text("contact_phone").notNull(),
  clientType: clientTypeEnum('client_type').notNull(),
  billingFrequency: billingFrequencyEnum('billing_frequency').notNull(),
  billingAddress: text("billing_address"),
  physicalAddress: text("physical_address"),
  postalCode: text("postal_code"),
  city: text("city"),
  country: text("country").default('Kenya'),
  website: text("website"),
  taxId: text("tax_id"),
  industry: text("industry"),
  numberOfEmployees: integer("number_of_employees").default(0),
  annualRevenue: decimal("annual_revenue", { precision: 15, scale: 2 }),
  creditLimit: decimal("credit_limit", { precision: 15, scale: 2 }),
  creditRating: text("credit_rating"),
  paymentTerms: text("payment_terms"),
  isApproved: boolean("is_approved").default(false),
  approvedBy: integer("approved_by"),
  approvedAt: timestamp("approved_at"),
  isActive: boolean("is_active").default(true),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  nameIdx: index('companies_name_idx').on(table.name),
  registrationNumberIdx: index('companies_registration_number_idx').on(table.registrationNumber),
  clientTypeIdx: index('companies_client_type_idx').on(table.clientType),
  billingFrequencyIdx: index('companies_billing_frequency_idx').on(table.billingFrequency),
  isActiveIdx: index('companies_is_active_idx').on(table.isActive),
  approvedAtIdx: index('companies_approved_at_idx').on(table.approvedAt),
}));

// Members table
export const members = pgTable("members", {
  id: serial("id").primaryKey(),
  memberNumber: text("member_number").notNull().unique(),
  companyId: integer("company_id").references(() => companies.id).notNull(),
  principalId: integer("principal_id").references(() => members.id),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  middleName: text("middle_name"),
  dateOfBirth: date("date_of_birth").notNull(),
  gender: genderEnum('gender').notNull(),
  maritalStatus: maritalStatusEnum('marital_status').notNull(),
  nationalId: text("national_id").unique(),
  passportNumber: text("passport_number").unique(),
  phoneNumber: text("phone_number").notNull(),
  email: text("email").unique(),
  postalAddress: text("postal_address"),
  physicalAddress: text("physical_address"),
  postalCode: text("postal_code"),
  city: text("city"),
  country: text("country").default('Kenya'),
  occupation: text("occupation"),
  employer: text("employer"),
  department: text("department"),
  jobTitle: text("job_title"),
  employmentDate: date("employment_date"),
  annualIncome: decimal("annual_income", { precision: 15, scale: 2 }),
  nextOfKin: text("next_of_kin"),
  nextOfKinRelationship: text("next_of_kin_relationship"),
  nextOfKinPhone: text("next_of_kin_phone"),
  nextOfKinEmail: text("next_of_kin_email"),
  beneficiaryName: text("beneficiary_name"),
  beneficiaryRelationship: text("beneficiary_relationship"),
  beneficiaryPercentage: integer("beneficiary_percentage").default(100),
  beneficiaryPhone: text("beneficiary_phone"),
  beneficiaryEmail: text("beneficiary_email"),
  membershipStatus: membershipStatusEnum('membership_status').notNull().default('pending'),
  membershipType: memberTypeEnum('membership_type').notNull(),
  dependentType: dependentTypeEnum('dependent_type'),
  enrollmentDate: date("enrollment_date"),
  effectiveDate: date("effective_date"),
  terminationDate: date("termination_date"),
  terminationReason: text("termination_reason"),
  suspensionDate: date("suspension_date"),
  suspensionReason: text("suspension_reason"),
  reinstatementDate: date("reinstatement_date"),
  reinstatementReason: text("reinstatement_reason"),
  isPrimary: boolean("is_primary").default(false),
  isDependent: boolean("is_dependent").default(false),
  isPrincipal: boolean("is_principal").default(false),
  isEmployee: boolean("is_employee").default(false),
  isSpouse: boolean("is_spouse").default(false),
  isChild: boolean("is_child").default(false),
  isParent: boolean("is_parent").default(false),
  isGuardian: boolean("is_guardian").default(false),
  isStudent: boolean("is_student").default(false),
  isRetired: boolean("is_retired").default(false),
  isDisabled: boolean("is_disabled").default(false),
  isPregnant: boolean("is_pregnant").default(false),
  isSmoker: boolean("is_smoker").default(false),
  hasPreExistingConditions: boolean("has_pre_existing_conditions").default(false),
  preExistingConditions: text("pre_existing_conditions"),
  allergies: text("allergies"),
  medications: text("medications"),
  medicalHistory: text("medical_history"),
  height: real("height"),
  weight: real("weight"),
  bloodType: text("blood_type"),
  bloodPressure: text("blood_pressure"),
  cholesterol: text("cholesterol"),
  lastCheckupDate: date("last_checkup_date"),
  nextCheckupDate: date("next_checkup_date"),
  isVerified: boolean("is_verified").default(false),
  verifiedBy: integer("verified_by"),
  verifiedAt: timestamp("verified_at"),
  notes: text("notes"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  memberNumberIdx: index('members_member_number_idx').on(table.memberNumber),
  companyIdIdx: index('members_company_id_idx').on(table.companyId),
  principalIdIdx: index('members_principal_id_idx').on(table.principalId),
  firstNameIdx: index('members_first_name_idx').on(table.firstName),
  lastNameIdx: index('members_last_name_idx').on(table.lastName),
  nationalIdIdx: index('members_national_id_idx').on(table.nationalId),
  passportNumberIdx: index('members_passport_number_idx').on(table.passportNumber),
  phoneNumberIdx: index('members_phone_number_idx').on(table.phoneNumber),
  emailIdx: index('members_email_idx').on(table.email),
  membershipStatusIdx: index('members_membership_status_idx').on(table.membershipStatus),
  membershipTypeIdx: index('members_membership_type_idx').on(table.membershipType),
  dependentTypeIdx: index('members_dependent_type_idx').on(table.dependentType),
  enrollmentDateIdx: index('members_enrollment_date_idx').on(table.enrollmentDate),
  effectiveDateIdx: index('members_effective_date_idx').on(table.effectiveDate),
  terminationDateIdx: index('members_termination_date_idx').on(table.terminationDate),
  isVerifiedIdx: index('members_is_verified_idx').on(table.isVerified),
  createdAtIdx: index('members_created_at_idx').on(table.createdAt),
}));

// Life Events table
export const lifeEvents = pgTable("life_events", {
  id: serial("id").primaryKey(),
  memberId: integer("member_id").references(() => members.id).notNull(),
  companyId: integer("company_id").references(() => companies.id).notNull(),
  eventType: lifeEventTypeEnum('event_type').notNull(),
  eventDate: date("event_date").notNull(),
  effectiveDate: date("effective_date").notNull(),
  description: text("description"),
  reason: text("reason"),
  status: approvalStatusEnum('status').notNull().default('pending'),
  approvedBy: integer("approved_by"),
  approvedAt: timestamp("approved_at"),
  rejectedBy: integer("rejected_by"),
  rejectedAt: timestamp("rejected_at"),
  rejectionReason: text("rejection_reason"),
  notes: text("notes"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  memberIdIdx: index('life_events_member_id_idx').on(table.memberId),
  companyIdIdx: index('life_events_company_id_idx').on(table.companyId),
  eventTypeIdx: index('life_events_event_type_idx').on(table.eventType),
  eventDateIdx: index('life_events_event_date_idx').on(table.eventDate),
  effectiveDateIdx: index('life_events_effective_date_idx').on(table.effectiveDate),
  statusIdx: index('life_events_status_idx').on(table.status),
  createdAtIdx: index('life_events_created_at_idx').on(table.createdAt),
}));

// Documents table
export const documents = pgTable("documents", {
  id: serial("id").primaryKey(),
  memberId: integer("member_id").references(() => members.id).notNull(),
  companyId: integer("company_id").references(() => companies.id).notNull(),
  documentType: documentTypeEnum('document_type').notNull(),
  documentNumber: text("document_number").notNull(),
  issueDate: date("issue_date"),
  expiryDate: date("expiry_date"),
  issuingAuthority: text("issuing_authority"),
  issuingCountry: text("issuing_country"),
  documentUrl: text("document_url"),
  documentData: jsonb("document_data"),
  status: approvalStatusEnum('status').notNull().default('pending'),
  approvedBy: integer("approved_by"),
  approvedAt: timestamp("approved_at"),
  rejectedBy: integer("rejected_by"),
  rejectedAt: timestamp("rejected_at"),
  rejectionReason: text("rejection_reason"),
  notes: text("notes"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  memberIdIdx: index('documents_member_id_idx').on(table.memberId),
  companyIdIdx: index('documents_company_id_idx').on(table.companyId),
  documentTypeIdx: index('documents_document_type_idx').on(table.documentType),
  documentNumberIdx: index('documents_document_number_idx').on(table.documentNumber),
  statusIdx: index('documents_status_idx').on(table.status),
  createdAtIdx: index('documents_created_at_idx').on(table.createdAt),
}));

// Consents table
export const consents = pgTable("consents", {
  id: serial("id").primaryKey(),
  memberId: integer("member_id").references(() => members.id).notNull(),
  companyId: integer("company_id").references(() => companies.id).notNull(),
  consentType: consentTypeEnum('consent_type').notNull(),
  consentGiven: boolean("consent_given").notNull(),
  consentDate: date("consent_date").notNull(),
  consentMethod: text("consent_method"),
  consentIpAddress: text("consent_ip_address"),
  consentUserAgent: text("consent_user_agent"),
  consentUrl: text("consent_url"),
  consentVersion: text("consent_version"),
  consentText: text("consent_text"),
  withdrawalDate: date("withdrawal_date"),
  withdrawalReason: text("withdrawal_reason"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  memberIdIdx: index('consents_member_id_idx').on(table.memberId),
  companyIdIdx: index('consents_company_id_idx').on(table.companyId),
  consentTypeIdx: index('consents_consent_type_idx').on(table.consentType),
  consentDateIdx: index('consents_consent_date_idx').on(table.consentDate),
  createdAtIdx: index('consents_created_at_idx').on(table.createdAt),
}));

// Communications table
export const communications = pgTable("communications", {
  id: serial("id").primaryKey(),
  memberId: integer("member_id").references(() => members.id).notNull(),
  companyId: integer("company_id").references(() => companies.id).notNull(),
  communicationType: communicationTypeEnum('communication_type').notNull(),
  communicationChannel: communicationChannelEnum('communication_channel').notNull(),
  subject: text("subject"),
  message: text("message").notNull(),
  templateId: text("template_id"),
  templateData: jsonb("template_data"),
  sender: text("sender"),
  recipient: text("recipient"),
  cc: text("cc"),
  bcc: text("bcc"),
  attachments: text("attachments"),
  deliveryStatus: deliveryStatusEnum('delivery_status').notNull().default('pending'),
  deliveryAttempts: integer("delivery_attempts").default(0),
  deliveryError: text("delivery_error"),
  sentAt: timestamp("sent_at"),
  deliveredAt: timestamp("delivered_at"),
  openedAt: timestamp("opened_at"),
  clickedAt: timestamp("clicked_at"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  memberIdIdx: index('communications_member_id_idx').on(table.memberId),
  companyIdIdx: index('communications_company_id_idx').on(table.companyId),
  communicationTypeIdx: index('communications_communication_type_idx').on(table.communicationType),
  communicationChannelIdx: index('communications_communication_channel_idx').on(table.communicationChannel),
  deliveryStatusIdx: index('communications_delivery_status_idx').on(table.deliveryStatus),
  sentAtIdx: index('communications_sent_at_idx').on(table.sentAt),
  createdAtIdx: index('communications_created_at_idx').on(table.createdAt),
}));

// Eligibility table
export const eligibility = pgTable("eligibility", {
  id: serial("id").primaryKey(),
  memberId: integer("member_id").references(() => members.id).notNull(),
  companyId: integer("company_id").references(() => companies.id).notNull(),
  benefitId: integer("benefit_id"),
  periodId: integer("period_id"),
  isEligible: boolean("is_eligible").notNull(),
  eligibilityReason: text("eligibility_reason"),
  coverageStartDate: date("coverage_start_date"),
  coverageEndDate: date("coverage_end_date"),
  waitingPeriodDays: integer("waiting_period_days").default(0),
  waitingPeriodStartDate: date("waiting_period_start_date"),
  waitingPeriodEndDate: date("waiting_period_end_date"),
  waitingPeriodCompleted: boolean("waiting_period_completed").default(false),
  waitingPeriodCompletedAt: timestamp("waiting_period_completed_at"),
  limits: jsonb("limits"),
  usedLimits: jsonb("used_limits"),
  remainingLimits: jsonb("remaining_limits"),
  limitsResetDate: date("limits_reset_date"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull()
});
