import { z } from "zod";
export declare const memberTypeEnum: any;
export declare const dependentTypeEnum: any;
export declare const periodStatusEnum: any;
export declare const periodTypeEnum: any;
export declare const benefitCategoryEnum: any;
export declare const institutionTypeEnum: any;
export declare const personnelTypeEnum: any;
export declare const approvalStatusEnum: any;
export declare const claimStatusEnum: any;
export declare const premiumRateTypeEnum: any;
export declare const pricingMethodologyEnum: any;
export declare const riskAdjustmentTierEnum: any;
export declare const inflationCategoryEnum: any;
export declare const networkTierEnum: any;
export declare const contractStatusEnum: any;
export declare const tariffStatusEnum: any;
export declare const reimbursementModelEnum: any;
export declare const genderEnum: any;
export declare const maritalStatusEnum: any;
export declare const membershipStatusEnum: any;
export declare const clientTypeEnum: any;
export declare const billingFrequencyEnum: any;
export declare const lifeEventTypeEnum: any;
export declare const documentTypeEnum: any;
export declare const communicationTypeEnum: any;
export declare const communicationChannelEnum: any;
export declare const deliveryStatusEnum: any;
export declare const consentTypeEnum: any;
export declare const auditActionEnum: any;
export declare const auditEntityTypeEnum: any;
export declare const companies: any;
export declare const members: any;
export declare const periods: any;
export declare const premiumRates: any;
export declare const ageBandedRates: any;
export declare const familyRates: any;
export declare const companyPeriods: any;
export declare const premiums: any;
export declare const benefits: any;
export declare const companyBenefits: any;
export declare const leadSourceEnum: any;
export declare const leadStatusEnum: any;
export declare const leadPriorityEnum: any;
export declare const opportunityStageEnum: any;
export declare const activityTypeEnum: any;
export declare const territoryTypeEnum: any;
export declare const leads: any;
export declare const salesOpportunities: any;
export declare const salesActivities: any;
export declare const salesTeams: any;
export declare const territories: any;
export declare const agents: any;
export declare const commissionTiers: any;
export declare const commissionTransactionTypeEnum: any;
export declare const commissionTransactions: any;
export declare const agentPerformance: any;
export declare const triggerTypeEnum: any;
export declare const workflowExecutionStatusEnum: any;
export declare const campaignStatusEnum: any;
export declare const workflowDefinitions: any;
export declare const workflowExecutions: any;
export declare const emailCampaigns: any;
export declare const insertMemberSchema: any;
export declare const insertCompanySchema: any;
export declare const insertPeriodSchema: any;
export declare const insertPremiumRateSchema: any;
export declare const insertPremiumSchema: any;
export declare const insertBenefitSchema: any;
export declare const insertPrincipalMemberSchema: any;
export declare const insertDependentMemberSchema: any;
export type Company = typeof companies.$inferSelect;
export type InsertCompany = z.infer<typeof insertCompanySchema>;
export type Member = typeof members.$inferSelect;
export type InsertMember = z.infer<typeof insertMemberSchema>;
export type InsertPrincipalMember = z.infer<typeof insertPrincipalMemberSchema>;
export type InsertDependentMember = z.infer<typeof insertDependentMemberSchema>;
export type Period = typeof periods.$inferSelect;
export type InsertPeriod = z.infer<typeof insertPeriodSchema>;
export type PremiumRate = typeof premiumRates.$inferSelect;
export type InsertPremiumRate = z.infer<typeof insertPremiumRateSchema>;
export type Premium = typeof premiums.$inferSelect;
export type InsertPremium = z.infer<typeof insertPremiumSchema>;
export type Benefit = typeof benefits.$inferSelect;
export type InsertBenefit = z.infer<typeof insertBenefitSchema>;
export declare const regions: any;
export declare const medicalInstitutions: any;
export declare const providerNetworks: any;
export declare const providerNetworkAssignments: any;
export declare const providerContracts: any;
export declare const contractDocuments: any;
export declare const contractSignatures: any;
export declare const medicalPersonnel: any;
export declare const panelDocumentation: any;
export declare const diagnosisCodeTypeEnum: any;
export declare const fraudRiskLevelEnum: any;
export declare const diagnosisCodes: any;
export declare const claims: any;
export declare const insertCompanyBenefitSchema: any;
export declare const insertRegionSchema: any;
export declare const insertMedicalInstitutionSchema: any;
export declare const insertMedicalPersonnelSchema: any;
export declare const insertPanelDocumentationSchema: any;
export declare const insertClaimSchema: any;
export declare const insertCompanyPeriodSchema: any;
export declare const insertAgeBandedRateSchema: any;
export declare const insertFamilyRateSchema: any;
export declare const insertDiagnosisCodeSchema: any;
export type CompanyBenefit = typeof companyBenefits.$inferSelect;
export type InsertCompanyBenefit = z.infer<typeof insertCompanyBenefitSchema>;
export type Region = typeof regions.$inferSelect;
export type InsertRegion = z.infer<typeof insertRegionSchema>;
export type MedicalInstitution = typeof medicalInstitutions.$inferSelect;
export type InsertMedicalInstitution = z.infer<typeof insertMedicalInstitutionSchema>;
export type MedicalPersonnel = typeof medicalPersonnel.$inferSelect;
export type InsertMedicalPersonnel = z.infer<typeof insertMedicalPersonnelSchema>;
export type PanelDocumentation = typeof panelDocumentation.$inferSelect;
export type InsertPanelDocumentation = z.infer<typeof insertPanelDocumentationSchema>;
export type Claim = typeof claims.$inferSelect;
export type InsertClaim = z.infer<typeof insertClaimSchema>;
export type CompanyPeriod = typeof companyPeriods.$inferSelect;
export type InsertCompanyPeriod = z.infer<typeof insertCompanyPeriodSchema>;
export type AgeBandedRate = typeof ageBandedRates.$inferSelect;
export type InsertAgeBandedRate = z.infer<typeof insertAgeBandedRateSchema>;
export type FamilyRate = typeof familyRates.$inferSelect;
export type InsertFamilyRate = z.infer<typeof insertFamilyRateSchema>;
export type DiagnosisCode = typeof diagnosisCodes.$inferSelect;
export type InsertDiagnosisCode = z.infer<typeof insertDiagnosisCodeSchema>;
export declare const paymentTypeEnum: any;
export declare const paymentStatusEnum: any;
export declare const paymentMethodEnum: any;
export declare const procedureCategoryEnum: any;
export declare const agentTypeEnum: any;
export declare const licenseStatusEnum: any;
export declare const userTypeEnum: any;
export declare const tokenPurchaseTypeEnum: any;
export declare const tokenPurchaseStatusEnum: any;
export declare const subscriptionStatusEnum: any;
export declare const subscriptionFrequencyEnum: any;
export declare const autoTopupTriggerTypeEnum: any;
export declare const autoTopupScheduleFrequencyEnum: any;
export declare const notificationThresholdTypeEnum: any;
export declare const users: any;
export declare const userSessions: any;
export declare const auditLogs: any;
export declare const organizationTokenWallets: any;
export declare const tokenPackages: any;
export declare const tokenPurchases: any;
export declare const tokenSubscriptions: any;
export declare const autoTopupPolicies: any;
export declare const tokenBalanceHistory: any;
export declare const lowBalanceNotifications: any;
export declare const tokenUsageForecasts: any;
export declare const premiumPayments: any;
export declare const claimPayments: any;
export declare const providerDisbursements: any;
export declare const disbursementItems: any;
export declare const insuranceBalances: any;
export declare const enhancedPremiumCalculations: any;
export declare const riskAdjustmentFactors: any;
export declare const healthcareInflationRates: any;
export declare const actuarialRateTables: any;
export declare const insertPremiumPaymentSchema: any;
export declare const insertClaimPaymentSchema: any;
export declare const insertProviderDisbursementSchema: any;
export declare const insertDisbursementItemSchema: any;
export declare const insertInsuranceBalanceSchema: any;
export type PremiumPayment = typeof premiumPayments.$inferSelect;
export type InsertPremiumPayment = z.infer<typeof insertPremiumPaymentSchema>;
export type ClaimPayment = typeof claimPayments.$inferSelect;
export type InsertClaimPayment = z.infer<typeof insertClaimPaymentSchema>;
export type ProviderDisbursement = typeof providerDisbursements.$inferSelect;
export type InsertProviderDisbursement = z.infer<typeof insertProviderDisbursementSchema>;
export type DisbursementItem = typeof disbursementItems.$inferSelect;
export type InsertDisbursementItem = z.infer<typeof insertDisbursementItemSchema>;
export type InsuranceBalance = typeof insuranceBalances.$inferSelect;
export type InsertInsuranceBalance = z.infer<typeof insertInsuranceBalanceSchema>;
export declare const insertEnhancedPremiumCalculationSchema: any;
export declare const insertRiskAdjustmentFactorSchema: any;
export declare const insertHealthcareInflationRateSchema: any;
export declare const insertActuarialRateTableSchema: any;
export type EnhancedPremiumCalculation = typeof enhancedPremiumCalculations.$inferSelect;
export type InsertEnhancedPremiumCalculation = z.infer<typeof insertEnhancedPremiumCalculationSchema>;
export type RiskAdjustmentFactor = typeof riskAdjustmentFactors.$inferSelect;
export type InsertRiskAdjustmentFactor = z.infer<typeof insertRiskAdjustmentFactorSchema>;
export type HealthcareInflationRate = typeof healthcareInflationRates.$inferSelect;
export type InsertHealthcareInflationRate = z.infer<typeof insertHealthcareInflationRateSchema>;
export type ActuarialRateTable = typeof actuarialRateTables.$inferSelect;
export type InsertActuarialRateTable = z.infer<typeof insertActuarialRateTableSchema>;
export declare const medicalProcedures: any;
export declare const providerProcedureRates: any;
export declare const tariffCatalogs: any;
export declare const tariffItems: any;
export declare const pharmacyPriceLists: any;
export declare const consumablesPriceLists: any;
export declare const claimProcedureItems: any;
export declare const insertMedicalProcedureSchema: any;
export declare const insertProviderProcedureRateSchema: any;
export declare const insertClaimProcedureItemSchema: any;
export type MedicalProcedure = typeof medicalProcedures.$inferSelect;
export type InsertMedicalProcedure = z.infer<typeof insertMedicalProcedureSchema>;
export type ProviderProcedureRate = typeof providerProcedureRates.$inferSelect;
export type InsertProviderProcedureRate = z.infer<typeof insertProviderProcedureRateSchema>;
export type ClaimProcedureItem = typeof claimProcedureItems.$inferSelect;
export type InsertClaimProcedureItem = z.infer<typeof insertClaimProcedureItemSchema>;
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type UserSession = typeof userSessions.$inferSelect;
export type InsertUserSession = z.infer<typeof insertUserSessionSchema>;
export type AuditLog = typeof auditLogs.$inferSelect;
export type InsertAuditLog = z.infer<typeof insertAuditLogSchema>;
export declare const onboardingStatusEnum: any;
export declare const taskTypeEnum: any;
export declare const documentStatusEnum: any;
export declare const activationStatusEnum: any;
export declare const onboardingSessions: any;
export declare const onboardingTasks: any;
export declare const memberDocuments: any;
export declare const onboardingPreferences: any;
export declare const activationTokens: any;
export declare const personalizationLevelEnum: any;
export declare const recommendationTypeEnum: any;
export declare const journeyStageEnum: any;
export declare const memberPreferences: any;
export declare const behaviorAnalytics: any;
export declare const personalizationScores: any;
export declare const journeyStages: any;
export declare const recommendationHistory: any;
export type OnboardingSession = typeof onboardingSessions.$inferSelect;
export type InsertOnboardingSession = z.infer<typeof insertOnboardingSessionSchema>;
export type OnboardingTask = typeof onboardingTasks.$inferSelect;
export type InsertOnboardingTask = z.infer<typeof insertOnboardingTaskSchema>;
export type MemberDocument = typeof memberDocuments.$inferSelect;
export type InsertMemberDocument = z.infer<typeof insertMemberDocumentSchema>;
export type OnboardingPreference = typeof onboardingPreferences.$inferSelect;
export type InsertOnboardingPreference = z.infer<typeof insertOnboardingPreferenceSchema>;
export type ActivationToken = typeof activationTokens.$inferSelect;
export type InsertActivationToken = z.infer<typeof insertActivationTokenSchema>;
export type MemberPreference = typeof memberPreferences.$inferSelect;
export type InsertMemberPreference = z.infer<typeof insertMemberPreferenceSchema>;
export type BehaviorAnalytic = typeof behaviorAnalytics.$inferSelect;
export type InsertBehaviorAnalytic = z.infer<typeof insertBehaviorAnalyticSchema>;
export type PersonalizationScore = typeof personalizationScores.$inferSelect;
export type InsertPersonalizationScore = z.infer<typeof insertPersonalizationScoreSchema>;
export type JourneyStage = typeof journeyStages.$inferSelect;
export type InsertJourneyStage = z.infer<typeof insertJourneyStageSchema>;
export type RecommendationHistory = typeof recommendationHistory.$inferSelect;
export type InsertRecommendationHistory = z.infer<typeof insertRecommendationHistorySchema>;
export declare const adjudicationResultEnum: any;
export declare const medicalNecessityResultEnum: any;
export declare const eobStatusEnum: any;
export declare const claimEventTypeEnum: any;
export declare const claimAdjudicationResults: any;
export declare const medicalNecessityValidations: any;
export declare const fraudDetectionResults: any;
export declare const explanationOfBenefits: any;
export declare const claimAuditTrails: any;
export declare const benefitUtilization: any;
export type ClaimAdjudicationResult = typeof claimAdjudicationResults.$inferSelect;
export type InsertClaimAdjudicationResult = z.infer<typeof insertClaimAdjudicationResultSchema>;
export type MedicalNecessityValidation = typeof medicalNecessityValidations.$inferSelect;
export type InsertMedicalNecessityValidation = z.infer<typeof insertMedicalNecessityValidationSchema>;
export type FraudDetectionResult = typeof fraudDetectionResults.$inferSelect;
export type InsertFraudDetectionResult = z.infer<typeof insertFraudDetectionResultSchema>;
export type ExplanationOfBenefits = typeof explanationOfBenefits.$inferSelect;
export type InsertExplanationOfBenefits = z.infer<typeof insertExplanationOfBenefitsSchema>;
export type ClaimAuditTrail = typeof claimAuditTrails.$inferSelect;
export type InsertClaimAuditTrail = z.infer<typeof insertClaimAuditTrailSchema>;
export type BenefitUtilization = typeof benefitUtilization.$inferSelect;
export type InsertBenefitUtilization = z.infer<typeof insertBenefitUtilizationSchema>;
export declare const cardTypeEnum: any;
export declare const cardStatusEnum: any;
export declare const cardTemplateEnum: any;
export declare const memberCards: any;
export declare const cardTemplates: any;
export declare const cardVerificationEvents: any;
export declare const cardProductionBatches: any;
export type MemberCard = typeof memberCards.$inferSelect;
export type InsertMemberCard = z.infer<typeof insertMemberCardSchema>;
export type CardTemplate = typeof cardTemplates.$inferSelect;
export type InsertCardTemplate = z.infer<typeof insertCardTemplateSchema>;
export type CardVerificationEvent = typeof cardVerificationEvents.$inferSelect;
export type InsertCardVerificationEvent = z.infer<typeof insertCardVerificationEventSchema>;
export type CardProductionBatch = typeof cardProductionBatches.$inferSelect;
export type InsertCardProductionBatch = z.infer<typeof insertCardProductionBatchSchema>;
export type ProviderNetwork = typeof providerNetworks.$inferSelect;
export type InsertProviderNetwork = z.infer<typeof insertProviderNetworkSchema>;
export type ProviderNetworkAssignment = typeof providerNetworkAssignments.$inferSelect;
export type InsertProviderNetworkAssignment = z.infer<typeof insertProviderNetworkAssignmentSchema>;
export type ProviderContract = typeof providerContracts.$inferSelect;
export type InsertProviderContract = z.infer<typeof insertProviderContractSchema>;
export type ContractDocument = typeof contractDocuments.$inferSelect;
export type InsertContractDocument = z.infer<typeof insertContractDocumentSchema>;
export type ContractSignature = typeof contractSignatures.$inferSelect;
export type InsertContractSignature = z.infer<typeof insertContractSignatureSchema>;
export type TariffCatalog = typeof tariffCatalogs.$inferSelect;
export type InsertTariffCatalog = z.infer<typeof insertTariffCatalogSchema>;
export type TariffItem = typeof tariffItems.$inferSelect;
export type InsertTariffItem = z.infer<typeof insertTariffItemSchema>;
export type PharmacyPriceList = typeof pharmacyPriceLists.$inferSelect;
export type InsertPharmacyPriceList = z.infer<typeof insertPharmacyPriceListSchema>;
export type ConsumablesPriceList = typeof consumablesPriceLists.$inferSelect;
export type InsertConsumablesPriceList = z.infer<typeof insertConsumablesPriceListSchema>;
export declare const schemeTypeEnum: any;
export declare const pricingModelEnum: any;
export declare const targetMarketEnum: any;
export declare const planTierEnum: any;
export declare const costSharingTypeEnum: any;
export declare const limitTypeEnum: any;
export declare const limitCategoryEnum: any;
export declare const frequencyLimitEnum: any;
export declare const employeeGradeEnum: any;
export declare const ruleCategoryEnum: any;
export declare const ruleTypeEnum: any;
export declare const ruleResultEnum: any;
export declare const providerVerificationStatusEnum: any;
export declare const providerOnboardingStatusEnum: any;
export declare const providerPerformanceTierEnum: any;
export declare const accreditationStatusEnum: any;
export declare const complianceStatusEnum: any;
export declare const providerOnboardingApplications: any;
export declare const providerVerificationChecklist: any;
export declare const providerAccreditations: any;
export declare const providerPerformanceMetrics: any;
export declare const providerComplianceMonitoring: any;
export declare const providerQualityScores: any;
export declare const providerFinancialPerformance: any;
export declare const providerReferralNetwork: any;
export declare const providerEducationTraining: any;
export declare const providerClinicalExpertise: any;
export type ProviderOnboardingApplication = typeof providerOnboardingApplications.$inferSelect;
export type InsertProviderOnboardingApplication = z.infer<typeof insertProviderOnboardingApplicationSchema>;
export type ProviderVerificationChecklist = typeof providerVerificationChecklist.$inferSelect;
export type InsertProviderVerificationChecklist = z.infer<typeof insertProviderVerificationChecklistSchema>;
export type ProviderAccreditation = typeof providerAccreditations.$inferSelect;
export type InsertProviderAccreditation = z.infer<typeof insertProviderAccreditationSchema>;
export type ProviderPerformanceMetric = typeof providerPerformanceMetrics.$inferSelect;
export type InsertProviderPerformanceMetric = z.infer<typeof insertProviderPerformanceMetricSchema>;
export type ProviderComplianceMonitoring = typeof providerComplianceMonitoring.$inferSelect;
export type InsertProviderComplianceMonitoring = z.infer<typeof insertProviderComplianceMonitoringSchema>;
export type ProviderQualityScore = typeof providerQualityScores.$inferSelect;
export type InsertProviderQualityScore = z.infer<typeof insertProviderQualityScoreSchema>;
export type ProviderFinancialPerformance = typeof providerFinancialPerformance.$inferSelect;
export type InsertProviderFinancialPerformance = z.infer<typeof insertProviderFinancialPerformanceSchema>;
export type ProviderReferralNetwork = typeof providerReferralNetwork.$inferSelect;
export type InsertProviderReferralNetwork = z.infer<typeof insertProviderReferralNetworkSchema>;
export type ProviderEducationTraining = typeof providerEducationTraining.$inferSelect;
export type InsertProviderEducationTraining = z.infer<typeof insertProviderEducationTrainingSchema>;
export type ProviderClinicalExpertise = typeof providerClinicalExpertise.$inferSelect;
export type InsertProviderClinicalExpertise = z.infer<typeof insertProviderClinicalExpertiseSchema>;
export type Scheme = typeof schemes.$inferSelect;
export type InsertScheme = z.infer<typeof insertSchemeSchema>;
export type SchemeVersion = typeof schemeVersions.$inferSelect;
export type InsertSchemeVersion = z.infer<typeof insertSchemeVersionSchema>;
export type PlanTier = typeof planTiers.$inferSelect;
export type InsertPlanTier = z.infer<typeof insertPlanTierSchema>;
export type EnhancedBenefit = typeof enhancedBenefits.$inferSelect;
export type InsertEnhancedBenefit = z.infer<typeof insertEnhancedBenefitSchema>;
export type SchemeBenefitMapping = typeof schemeBenefitMappings.$inferSelect;
export type InsertSchemeBenefitMapping = z.infer<typeof insertSchemeBenefitMappingSchema>;
export type CostSharingRule = typeof costSharingRules.$inferSelect;
export type InsertCostSharingRule = z.infer<typeof insertCostSharingRuleSchema>;
export type BenefitLimit = typeof benefitLimits.$inferSelect;
export type InsertBenefitLimit = z.infer<typeof insertBenefitLimitSchema>;
export type CorporateSchemeConfig = typeof corporateSchemeConfigs.$inferSelect;
export type InsertCorporateSchemeConfig = z.infer<typeof insertCorporateSchemeConfigSchema>;
export type EmployeeGradeBenefit = typeof employeeGradeBenefits.$inferSelect;
export type InsertEmployeeGradeBenefit = z.infer<typeof insertEmployeeGradeBenefitSchema>;
export type DependentCoverageRule = typeof dependentCoverageRules.$inferSelect;
export type InsertDependentCoverageRule = z.infer<typeof insertDependentCoverageRuleSchema>;
export type BenefitRider = typeof benefitRiders.$inferSelect;
export type InsertBenefitRider = z.infer<typeof insertBenefitRiderSchema>;
export type MemberRiderSelection = typeof memberRiderSelections.$inferSelect;
export type InsertMemberRiderSelection = z.infer<typeof insertMemberRiderSelectionSchema>;
export type BenefitRule = typeof benefitRules.$inferSelect;
export type InsertBenefitRule = z.infer<typeof insertBenefitRuleSchema>;
export type RuleExecutionLog = typeof ruleExecutionLogs.$inferSelect;
export type InsertRuleExecutionLog = z.infer<typeof insertRuleExecutionLogSchema>;
export declare const schemes: any;
export declare const schemeVersions: any;
export declare const planTiers: any;
export declare const enhancedBenefits: any;
export declare const schemeBenefitMappings: any;
export declare const costSharingRules: any;
export declare const benefitLimits: any;
export declare const corporateSchemeConfigs: any;
export declare const employeeGradeBenefits: any;
export declare const dependentCoverageRules: any;
export declare const benefitRiders: any;
export declare const memberRiderSelections: any;
export declare const benefitRules: any;
export declare const ruleExecutionLogs: any;
export declare const memberLifeEvents: any;
export declare const dependentRules: any;
export declare const employeeGrades: any;
export declare const communicationLogs: any;
export declare const memberConsents: any;
export declare const wellnessActivities: any;
export declare const riskAssessments: any;
export declare const providers: any;
export declare const insertCompanyBenefitSchema: any;
export declare const insertRegionSchema: any;
export declare const insertMedicalInstitutionSchema: any;
export declare const insertMedicalPersonnelSchema: any;
export declare const insertPanelDocumentationSchema: any;
export declare const insertClaimSchema: any;
export declare const insertCompanyPeriodSchema: any;
export declare const insertAgeBandedRateSchema: any;
export declare const insertFamilyRateSchema: any;
export declare const insertDiagnosisCodeSchema: any;
export declare const insertPremiumPaymentSchema: any;
export declare const insertClaimPaymentSchema: any;
export declare const insertProviderDisbursementSchema: any;
export declare const insertDisbursementItemSchema: any;
export declare const insertInsuranceBalanceSchema: any;
export declare const insertEnhancedPremiumCalculationSchema: any;
export declare const insertRiskAdjustmentFactorSchema: any;
export declare const insertHealthcareInflationRateSchema: any;
export declare const insertActuarialRateTableSchema: any;
export declare const insertMedicalProcedureSchema: any;
export declare const insertProviderProcedureRateSchema: any;
export declare const insertClaimProcedureItemSchema: any;
export declare const insertUserSchema: any;
export declare const insertUserSessionSchema: any;
export declare const insertAuditLogSchema: any;
export declare const insertOnboardingSessionSchema: any;
export declare const insertOnboardingTaskSchema: any;
export declare const insertMemberDocumentSchema: any;
export declare const insertOnboardingPreferenceSchema: any;
export declare const insertActivationTokenSchema: any;
export declare const insertMemberPreferenceSchema: any;
export declare const insertBehaviorAnalyticSchema: any;
export declare const insertPersonalizationScoreSchema: any;
export declare const insertJourneyStageSchema: any;
export declare const insertRecommendationHistorySchema: any;
export declare const insertClaimAdjudicationResultSchema: any;
export declare const insertMedicalNecessityValidationSchema: any;
export declare const insertFraudDetectionResultSchema: any;
export declare const insertExplanationOfBenefitsSchema: any;
export declare const insertClaimAuditTrailSchema: any;
export declare const insertBenefitUtilizationSchema: any;
export declare const insertMemberCardSchema: any;
export declare const insertCardTemplateSchema: any;
export declare const insertCardVerificationEventSchema: any;
export declare const insertCardProductionBatchSchema: any;
export declare const insertProviderNetworkSchema: any;
export declare const insertProviderNetworkAssignmentSchema: any;
export declare const insertProviderContractSchema: any;
export declare const insertContractDocumentSchema: any;
export declare const insertContractSignatureSchema: any;
export declare const insertTariffCatalogSchema: any;
export declare const insertTariffItemSchema: any;
export declare const insertPharmacyPriceListSchema: any;
export declare const insertConsumablesPriceListSchema: any;
export declare const insertProviderOnboardingApplicationSchema: any;
export declare const insertProviderVerificationChecklistSchema: any;
export declare const insertProviderAccreditationSchema: any;
export declare const insertProviderPerformanceMetricSchema: any;
export declare const insertProviderComplianceMonitoringSchema: any;
export declare const insertProviderQualityScoreSchema: any;
export declare const insertProviderFinancialPerformanceSchema: any;
export declare const insertProviderReferralNetworkSchema: any;
export declare const insertProviderEducationTrainingSchema: any;
export declare const insertProviderClinicalExpertiseSchema: any;
export declare const insertSchemeSchema: any;
export declare const insertSchemeVersionSchema: any;
export declare const insertPlanTierSchema: any;
export declare const insertEnhancedBenefitSchema: any;
export declare const insertSchemeBenefitMappingSchema: any;
export declare const insertCostSharingRuleSchema: any;
export declare const insertBenefitLimitSchema: any;
export declare const insertCorporateSchemeConfigSchema: any;
export declare const insertEmployeeGradeBenefitSchema: any;
export declare const insertDependentCoverageRuleSchema: any;
export declare const insertBenefitRiderSchema: any;
export declare const insertMemberRiderSelectionSchema: any;
export declare const insertBenefitRuleSchema: any;
export declare const insertRuleExecutionLogSchema: any;
export declare const taskStatusEnum: any;
export declare const taskPriorityEnum: any;
export declare const taskCategoryEnum: any;
export declare const tasks: any;
export declare const taskTemplates: any;
export declare const notificationTypeEnum: any;
export declare const notificationChannelEnum: any;
export declare const notificationPriorityEnum: any;
export declare const notificationStatusEnum: any;
export declare const notifications: any;
export declare const notificationTemplates: any;
export declare const notificationPreferences: any;
export declare const insertLeadSchema: any;
export declare const insertSalesOpportunitySchema: any;
export declare const insertSalesActivitySchema: any;
export declare const insertSalesTeamSchema: any;
export declare const insertTerritorySchema: any;
export declare const insertAgentSchema: any;
export declare const insertCommissionTierSchema: any;
export declare const insertCommissionTransactionSchema: any;
export declare const insertAgentPerformanceSchema: any;
export declare const insertWorkflowDefinitionSchema: any;
export declare const insertWorkflowExecutionSchema: any;
export declare const insertEmailCampaignSchema: any;
export declare const insertTaskSchema: any;
export declare const insertTaskTemplateSchema: any;
export declare const insertNotificationSchema: any;
export declare const insertNotificationTemplateSchema: any;
export declare const insertNotificationPreferenceSchema: any;
export declare const invoiceStatusEnum: any;
export declare const invoiceTypeEnum: any;
export declare const lineItemTypeEnum: any;
export declare const arAccountStatusEnum: any;
export declare const collectionStatusEnum: any;
export declare const billingCommunicationTypeEnum: any;
export declare const billingCommunicationStatusEnum: any;
export declare const billingChannelEnum: any;
export declare const invoices: any;
export declare const invoiceLineItems: any;
export declare const invoicePayments: any;
export declare const accountsReceivable: any;
export declare const billingCommunications: any;
export declare const billingCommunicationTemplates: any;
export declare const communicationRules: any;
export declare const collectionWorkflows: any;
export declare const collectionActions: any;
export declare const dunningRules: any;
export declare const insertInvoiceSchema: any;
export declare const insertInvoiceLineItemSchema: any;
export declare const insertInvoicePaymentSchema: any;
export declare const insertAccountsReceivableSchema: any;
export declare const insertBillingCommunicationSchema: any;
export declare const insertBillingCommunicationTemplateSchema: any;
export declare const insertCommunicationRuleSchema: any;
export declare const insertCollectionWorkflowSchema: any;
export declare const insertCollectionActionSchema: any;
export declare const insertDunningRuleSchema: any;
export type Invoice = typeof invoices.$inferSelect;
export type InsertInvoice = z.infer<typeof insertInvoiceSchema>;
export type InvoiceLineItem = typeof invoiceLineItems.$inferSelect;
export type InsertInvoiceLineItem = z.infer<typeof insertInvoiceLineItemSchema>;
export type InvoicePayment = typeof invoicePayments.$inferSelect;
export type InsertInvoicePayment = z.infer<typeof insertInvoicePaymentSchema>;
export type AccountsReceivable = typeof accountsReceivable.$inferSelect;
export type InsertAccountsReceivable = z.infer<typeof insertAccountsReceivableSchema>;
export type BillingCommunication = typeof billingCommunications.$inferSelect;
export type InsertBillingCommunication = z.infer<typeof insertBillingCommunicationSchema>;
export type BillingCommunicationTemplate = typeof billingCommunicationTemplates.$inferSelect;
export type InsertBillingCommunicationTemplate = z.infer<typeof insertBillingCommunicationTemplateSchema>;
export type CommunicationRule = typeof communicationRules.$inferSelect;
export type InsertCommunicationRule = z.infer<typeof insertCommunicationRuleSchema>;
export type CollectionWorkflow = typeof collectionWorkflows.$inferSelect;
export type InsertCollectionWorkflow = z.infer<typeof insertCollectionWorkflowSchema>;
export type CollectionAction = typeof collectionActions.$inferSelect;
export type InsertCollectionAction = z.infer<typeof insertCollectionActionSchema>;
export type DunningRule = typeof dunningRules.$inferSelect;
export type InsertDunningRule = z.infer<typeof insertDunningRuleSchema>;
export declare const financePaymentStatusEnum: any;
export declare const paymentMethodTypeEnum: any;
export declare const paymentGatewayTypeEnum: any;
export declare const paymentNotificationTypeEnum: any;
export declare const paymentNotificationChannelEnum: any;
export declare const paymentNotificationStatusEnum: any;
export declare const reconciliationStatusEnum: any;
export declare const exceptionTypeEnum: any;
export declare const exceptionSeverityEnum: any;
export declare const paymentReversalTypeEnum: any;
export declare const payments: any;
export declare const paymentMethods: any;
export declare const paymentAllocations: any;
export declare const paymentReconciliations: any;
export declare const bankStatementImports: any;
export declare const bankTransactions: any;
export declare const paymentReversals: any;
export declare const paymentNotifications: any;
export declare const paymentNotificationTemplates: any;
export declare const reconciliationExceptions: any;
export declare const insertPaymentSchema: any;
export declare const insertPaymentMethodSchema: any;
export declare const insertPaymentAllocationSchema: any;
export declare const insertPaymentReconciliationSchema: any;
export declare const insertBankStatementImportSchema: any;
export declare const insertBankTransactionSchema: any;
export declare const insertPaymentReversalSchema: any;
export declare const insertPaymentNotificationSchema: any;
export declare const insertPaymentNotificationTemplateSchema: any;
export declare const insertReconciliationExceptionSchema: any;
export type Payment = typeof payments.$inferSelect;
export type InsertPayment = z.infer<typeof insertPaymentSchema>;
export type PaymentMethod = typeof paymentMethods.$inferSelect;
export type InsertPaymentMethod = z.infer<typeof insertPaymentMethodSchema>;
export type PaymentAllocation = typeof paymentAllocations.$inferSelect;
export type InsertPaymentAllocation = z.infer<typeof insertPaymentAllocationSchema>;
export type PaymentReconciliation = typeof paymentReconciliations.$inferSelect;
export type InsertPaymentReconciliation = z.infer<typeof insertPaymentReconciliationSchema>;
export type BankStatementImport = typeof bankStatementImports.$inferSelect;
export type InsertBankStatementImport = z.infer<typeof insertBankStatementImportSchema>;
export type BankTransaction = typeof bankTransactions.$inferSelect;
export type InsertBankTransaction = z.infer<typeof insertBankTransactionSchema>;
export type PaymentReversal = typeof paymentReversals.$inferSelect;
export type InsertPaymentReversal = z.infer<typeof insertPaymentReversalSchema>;
export type PaymentNotification = typeof paymentNotifications.$inferSelect;
export type InsertPaymentNotification = z.infer<typeof insertPaymentNotificationSchema>;
export type PaymentNotificationTemplate = typeof paymentNotificationTemplates.$inferSelect;
export type InsertPaymentNotificationTemplate = z.infer<typeof insertPaymentNotificationTemplateSchema>;
export type ReconciliationException = typeof reconciliationExceptions.$inferSelect;
export type InsertReconciliationException = z.infer<typeof insertReconciliationExceptionSchema>;
export declare const commissionStatusEnum: any;
export declare const commissionFinanceTransactionTypeEnum: any;
export declare const clawbackTypeEnum: any;
export declare const paymentRunStatusEnum: any;
export declare const auditStatusEnum: any;
export declare const auditTypeEnum: any;
export declare const findingTypeEnum: any;
export declare const findingSeverityEnum: any;
export declare const adjustmentTypeEnum: any;
export declare const taxTypeEnum: any;
export declare const taxCalculationMethodEnum: any;
export declare const reportStatusEnum: any;
export declare const reportTypeEnum: any;
export declare const leaderboardCategoryEnum: any;
export declare const performancePeriodTypeEnum: any;
export declare const commissionAccruals: any;
export declare const commissionPaymentRuns: any;
export declare const agentCommissionPayments: any;
export declare const paymentRunAdjustments: any;
export declare const paymentRunExceptions: any;
export declare const taxConfigurations: any;
export declare const taxWithholdingCalculations: any;
export declare const commissionAudits: any;
export declare const auditFindings: any;
export declare const agentPerformanceMetrics: any;
export declare const agentLeaderboards: any;
export declare const commissionReports: any;
export declare const policies: any;
export declare const insertCommissionAccrualSchema: any;
export declare const insertCommissionPaymentRunSchema: any;
export declare const insertAgentCommissionPaymentSchema: any;
export declare const insertPaymentRunAdjustmentSchema: any;
export declare const insertPaymentRunExceptionSchema: any;
export declare const insertTaxConfigurationSchema: any;
export declare const insertTaxWithholdingCalculationSchema: any;
export declare const insertCommissionAuditSchema: any;
export declare const insertAuditFindingSchema: any;
export declare const insertAgentPerformanceMetricSchema: any;
export declare const insertAgentLeaderboardSchema: any;
export declare const insertCommissionReportSchema: any;
export declare const insertPolicySchema: any;
export type CommissionAccrual = typeof commissionAccruals.$inferSelect;
export type InsertCommissionAccrual = z.infer<typeof insertCommissionAccrualSchema>;
export type CommissionPaymentRun = typeof commissionPaymentRuns.$inferSelect;
export type InsertCommissionPaymentRun = z.infer<typeof insertCommissionPaymentRunSchema>;
export type AgentCommissionPayment = typeof agentCommissionPayments.$inferSelect;
export type InsertAgentCommissionPayment = z.infer<typeof insertAgentCommissionPaymentSchema>;
export type PaymentRunAdjustment = typeof paymentRunAdjustments.$inferSelect;
export type InsertPaymentRunAdjustment = z.infer<typeof insertPaymentRunAdjustmentSchema>;
export type PaymentRunException = typeof paymentRunExceptions.$inferSelect;
export type InsertPaymentRunException = z.infer<typeof insertPaymentRunExceptionSchema>;
export type TaxConfiguration = typeof taxConfigurations.$inferSelect;
export type InsertTaxConfiguration = z.infer<typeof insertTaxConfigurationSchema>;
export type TaxWithholdingCalculation = typeof taxWithholdingCalculations.$inferSelect;
export type InsertTaxWithholdingCalculation = z.infer<typeof insertTaxWithholdingCalculationSchema>;
export type CommissionAudit = typeof commissionAudits.$inferSelect;
export type InsertCommissionAudit = z.infer<typeof insertCommissionAuditSchema>;
export type AuditFinding = typeof auditFindings.$inferSelect;
export type InsertAuditFinding = z.infer<typeof insertAuditFindingSchema>;
export type AgentPerformanceMetric = typeof agentPerformanceMetrics.$inferSelect;
export type InsertAgentPerformanceMetric = z.infer<typeof insertAgentPerformanceMetricSchema>;
export type AgentLeaderboard = typeof agentLeaderboards.$inferSelect;
export type InsertAgentLeaderboard = z.infer<typeof insertAgentLeaderboardSchema>;
export type CommissionReport = typeof commissionReports.$inferSelect;
export type InsertCommissionReport = z.infer<typeof insertCommissionReportSchema>;
export type Policy = typeof policies.$inferSelect;
export type InsertPolicy = z.infer<typeof insertPolicySchema>;
export declare enum ClaimReserveType {
    INCURRED_LOSS = "INCURRED_LOSS",
    EXPENSE = "EXPENSE",
    SALVAGE_RECOVERY = "SALVAGE_RECOVERY",
    LEGAL_EXPENSES = "LEGAL_EXPENSES"
}
export declare enum ClaimReserveStatus {
    ACTIVE = "ACTIVE",
    CLOSED = "CLOSED",
    EXHAUSTED = "EXHAUSTED",
    SUPERSEDED = "SUPERSEDED"
}
export declare enum ClaimPaymentType {
    INDEMNITY = "INDEMNITY",
    EXPENSE = "EXPENSE",
    LEGAL = "LEGAL",
    MEDICAL = "MEDICAL",
    REHABILITATION = "REHABILITATION",
    LOSS_OF_EARNINGS = "LOSS_OF_EARNINGS"
}
export declare enum ClaimPaymentStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    PROCESSING = "PROCESSING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    REJECTED = "REJECTED",
    CANCELLED = "CANCELLED",
    ESCALATED = "ESCALATED"
}
export declare enum ClaimApprovalStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    CANCELLED = "CANCELLED",
    COMPLETED = "COMPLETED"
}
export declare enum FinancialTransactionType {
    PAYMENT_REQUEST = "PAYMENT_REQUEST",
    PAYMENT_EXECUTION = "PAYMENT_EXECUTION",
    RESERVE_INCREASE = "RESERVE_INCREASE",
    RESERVE_DECREASE = "RESERVE_DECREASE",
    RECOVERY_RECEIVED = "RECOVERY_RECEIVED",
    EXPENSE_ALLOCATION = "EXPENSE_ALLOCATION"
}
export declare enum FinancialTransactionStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    POSTED = "POSTED",
    REJECTED = "REJECTED",
    FAILED = "FAILED"
}
export declare const claimReserves: any;
export declare const claimReserveTransactions: any;
export declare const claimFinancePayments: any;
export declare const claimApprovalWorkflows: any;
export declare const claimApprovalSteps: any;
export declare const claimFinancialTransactions: any;
export declare const claimAnalytics: any;
export declare const claimFinancialMetrics: any;
export declare const claimReserveTypeEnum: any;
export declare const claimReserveStatusEnum: any;
export declare const claimPaymentTypeEnum: any;
export declare const claimPaymentStatusEnum: any;
export declare const claimApprovalStatusEnum: any;
export declare const financialTransactionTypeEnum: any;
export declare const financialTransactionStatusEnum: any;
export declare const insertClaimReserveSchema: any;
export declare const insertClaimReserveTransactionSchema: any;
export declare const insertClaimFinancePaymentSchema: any;
export declare const insertClaimApprovalWorkflowSchema: any;
export declare const insertClaimApprovalStepSchema: any;
export declare const insertClaimFinancialTransactionSchema: any;
export declare const insertClaimAnalyticsSchema: any;
export declare const insertClaimFinancialMetricsSchema: any;
export type ClaimReserve = typeof claimReserves.$inferSelect;
export type InsertClaimReserve = z.infer<typeof insertClaimReserveSchema>;
export type ClaimReserveTransaction = typeof claimReserveTransactions.$inferSelect;
export type InsertClaimReserveTransaction = z.infer<typeof insertClaimReserveTransactionSchema>;
export type ClaimPayment = typeof claimFinancePayments.$inferSelect;
export type InsertClaimPayment = z.infer<typeof insertClaimFinancePaymentSchema>;
export type ClaimApprovalWorkflow = typeof claimApprovalWorkflows.$inferSelect;
export type InsertClaimApprovalWorkflow = z.infer<typeof insertClaimApprovalWorkflowSchema>;
export type ClaimApprovalStep = typeof claimApprovalSteps.$inferSelect;
export type InsertClaimApprovalStep = z.infer<typeof insertClaimApprovalStepSchema>;
export type ClaimFinancialTransaction = typeof claimFinancialTransactions.$inferSelect;
export type InsertClaimFinancialTransaction = z.infer<typeof insertClaimFinancialTransactionSchema>;
export type ClaimAnalytics = typeof claimAnalytics.$inferSelect;
export type InsertClaimAnalytics = z.infer<typeof insertClaimAnalyticsSchema>;
export type ClaimFinancialMetrics = typeof claimFinancialMetrics.$inferSelect;
export type InsertClaimFinancialMetrics = z.infer<typeof insertClaimFinancialMetricsSchema>;
export type ClaimCostBreakdown = {
    indemnityPayments: number;
    expensePayments: number;
    legalExpenses: number;
    administrativeCosts: number;
};
export type ClaimPaymentPatterns = {
    paymentFrequency: number;
    averagePaymentAmount: number;
    paymentTiming: any;
    seasonalPatterns: any;
};
export type ClaimReserveAnalysis = {
    initialReserve: number;
    finalReserve: number;
    reserveChanges: number;
    adequacyRatio: number;
    reserveAccuracy: number;
};
export type ClaimLossRatioAnalysis = {
    incurredLoss: number;
    earnedPremium: number;
    lossRatio: number;
    expenseRatio: number;
    combinedRatio: number;
};
export declare const fraudAlertSeverityEnum: any;
export declare const fraudAlertStatusEnum: any;
export declare const fraudRuleTypeEnum: any;
export declare const fraudRuleStatusEnum: any;
export declare const fraudInvestigationStatusEnum: any;
export declare const fraudInvestigationPriorityEnum: any;
export declare const mlModelTypeEnum: any;
export declare const mlModelStatusEnum: any;
export declare const behavioralPatternTypeEnum: any;
export declare const networkAnalysisTypeEnum: any;
export declare const riskScoreLevelEnum: any;
export declare const fraudAnalyticsPeriodEnum: any;
export declare const fraudAlerts: any;
export declare const fraudRules: any;
export declare const fraudInvestigations: any;
export declare const mlModels: any;
export declare const behavioralProfiles: any;
export declare const networkAnalysis: any;
export declare const riskScores: any;
export declare const fraudAnalytics: any;
export declare const insertFraudAlertSchema: any;
export declare const insertFraudRuleSchema: any;
export declare const insertFraudInvestigationSchema: any;
export declare const insertMlModelSchema: any;
export declare const insertBehavioralProfileSchema: any;
export declare const insertNetworkAnalysisSchema: any;
export declare const insertRiskScoreSchema: any;
export declare const insertFraudAnalyticsSchema: any;
export type FraudAlert = typeof fraudAlerts.$inferSelect;
export type InsertFraudAlert = z.infer<typeof insertFraudAlertSchema>;
export type FraudRule = typeof fraudRules.$inferSelect;
export type InsertFraudRule = z.infer<typeof insertFraudRuleSchema>;
export type FraudInvestigation = typeof fraudInvestigations.$inferSelect;
export type InsertFraudInvestigation = z.infer<typeof insertFraudInvestigationSchema>;
export type MlModel = typeof mlModels.$inferSelect;
export type InsertMlModel = z.infer<typeof insertMlModelSchema>;
export type BehavioralProfile = typeof behavioralProfiles.$inferSelect;
export type InsertBehavioralProfile = z.infer<typeof insertBehavioralProfileSchema>;
export type NetworkAnalysis = typeof networkAnalysis.$inferSelect;
export type InsertNetworkAnalysis = z.infer<typeof insertNetworkAnalysisSchema>;
export type RiskScore = typeof riskScores.$inferSelect;
export type InsertRiskScore = z.infer<typeof insertRiskScoreSchema>;
export type FraudAnalytics = typeof fraudAnalytics.$inferSelect;
export type InsertFraudAnalytics = z.infer<typeof insertFraudAnalyticsSchema>;
