import { config } from '../config/index.js';
import { createLogger } from '../utils/logger.js';

const logger = createLogger();

export interface AutomatedAction {
  id: string;
  claimId: number;
  actionType: 'auto_deny' | 'auto_review' | 'initiate_recovery' | 'member_notification' | 'provider_notification';
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  reason: string;
  metadata: Record<string, any>;
  createdAt: string;
  completedAt?: string;
  result?: Record<string, any>;
  error?: string;
}

export class AutomatedActionsService {
  private actions: Map<string, AutomatedAction> = new Map();

  /**
   * Process fraud detection result and trigger automated actions
   */
  async processDetectionResult(
    claimId: number,
    riskScore: number,
    riskLevel: 'low' | 'medium' | 'high' | 'critical',
    detectedIndicators: string[],
    recommendedAction: string
  ): Promise<AutomatedAction[]> {
    const triggeredActions: AutomatedAction[] = [];

    logger.info(`Processing detection result for claim ${claimId}`, {
      claimId,
      riskScore,
      riskLevel,
      recommendedAction,
    });

    try {
      // Auto-deny if critical fraud detected and enabled
      if (
        riskLevel === 'critical' &&
        config.automatedActions.autoDenialEnabled &&
        recommendedAction === 'investigate'
      ) {
        const denialAction = await this.autoDenyClaim(claimId, riskLevel, detectedIndicators);
        triggeredActions.push(denialAction);
      }

      // Initiate recovery if fraud confirmed
      if (riskLevel === 'critical' && config.automatedActions.autoRecoveryEnabled) {
        const recoveryAction = await this.initiateRecovery(claimId, riskScore);
        triggeredActions.push(recoveryAction);
      }

      // Send notifications based on risk level
      if (riskLevel === 'high' || riskLevel === 'critical') {
        const notificationActions = await this.sendFraudNotifications(claimId, riskLevel);
        triggeredActions.push(...notificationActions);
      }

      // Queue for manual review if high risk
      if (riskLevel === 'high') {
        const reviewAction = await this.queueForManualReview(claimId, riskScore, detectedIndicators);
        triggeredActions.push(reviewAction);
      }

      logger.info(`Automated actions triggered for claim ${claimId}`, {
        claimId,
        actionCount: triggeredActions.length,
      });

      return triggeredActions;
    } catch (error) {
      logger.error(`Error processing detection result for claim ${claimId}`, {
        claimId,
        error: error instanceof Error ? error.message : 'Unknown error',
      });
      throw error;
    }
  }

  /**
   * Auto-deny a claim due to fraud
   */
  private async autoDenyClaim(
    claimId: number,
    riskLevel: string,
    indicators: string[]
  ): Promise<AutomatedAction> {
    const action: AutomatedAction = {
      id: `action_${claimId}_deny`,
      claimId,
      actionType: 'auto_deny',
      status: 'in_progress',
      reason: `Automatic denial due to ${riskLevel} fraud risk`,
      metadata: {
        indicators,
        denialReason: 'Suspected fraudulent claim activity',
        appealableAfterDays: 30,
      },
      createdAt: new Date().toISOString(),
    };

    try {
      // TODO: Call claims service API to deny claim
      // await claimsServiceClient.denyClaim(claimId, {
      //   reason: action.reason,
      //   fraudDetected: true,
      //   autoGenerated: true,
      // });

      action.status = 'completed';
      action.completedAt = new DateTime().toISOString();
      action.result = {
        claimDenied: true,
        denialDate: new Date().toISOString(),
        memberNotified: true,
      };

      logger.info(`Claim auto-denied`, {
        claimId,
        riskLevel,
        indicators: indicators.length,
      });
    } catch (error) {
      action.status = 'failed';
      action.error = error instanceof Error ? error.message : 'Unknown error';

      logger.error(`Failed to auto-deny claim ${claimId}`, {
        claimId,
        error: action.error,
      });
    }

    this.actions.set(action.id, action);
    return action;
  }

  /**
   * Initiate recovery process for fraudulent amounts
   */
  private async initiateRecovery(claimId: number, riskScore: number): Promise<AutomatedAction> {
    const action: AutomatedAction = {
      id: `action_${claimId}_recovery`,
      claimId,
      actionType: 'initiate_recovery',
      status: 'in_progress',
      reason: `Recovery process initiated for fraud risk score ${riskScore}`,
      metadata: {
        recoveryMultiplier: config.automatedActions.recoveryAmount,
        recoveryInitiatedDate: new Date().toISOString(),
      },
      createdAt: new Date().toISOString(),
    };

    try {
      // TODO: Call billing service to initiate recovery
      // const claimAmount = await claimsServiceClient.getClaimAmount(claimId);
      // const recoveryAmount = claimAmount * config.automatedActions.recoveryAmount;
      // await billingServiceClient.initiateRecovery(claimId, recoveryAmount);

      action.status = 'completed';
      action.completedAt = new Date().toISOString();
      action.result = {
        recoveryInitiated: true,
        initiatedDate: new Date().toISOString(),
        recoveryMultiplier: config.automatedActions.recoveryAmount,
      };

      logger.info(`Recovery initiated for claim ${claimId}`, {
        claimId,
        riskScore,
        recoveryMultiplier: config.automatedActions.recoveryAmount,
      });
    } catch (error) {
      action.status = 'failed';
      action.error = error instanceof Error ? error.message : 'Unknown error';

      logger.error(`Failed to initiate recovery for claim ${claimId}`, {
        claimId,
        error: action.error,
      });
    }

    this.actions.set(action.id, action);
    return action;
  }

  /**
   * Send fraud notifications to relevant parties
   */
  private async sendFraudNotifications(claimId: number, riskLevel: string): Promise<AutomatedAction[]> {
    const actions: AutomatedAction[] = [];

    // Member notification
    const memberAction: AutomatedAction = {
      id: `action_${claimId}_notify_member`,
      claimId,
      actionType: 'member_notification',
      status: 'pending',
      reason: `Notifying member of fraud investigation for claim`,
      metadata: {
        notificationType: 'fraud_investigation',
        riskLevel,
        sendMethod: ['email', 'sms'],
      },
      createdAt: new Date().toISOString(),
    };

    try {
      // TODO: Call notification service
      // await notificationService.notifyMember(claimId, {
      //   type: 'fraud_investigation',
      //   riskLevel,
      // });

      memberAction.status = 'completed';
      memberAction.completedAt = new Date().toISOString();
      memberAction.result = {
        emailSent: true,
        smsSent: true,
        notificationDate: new Date().toISOString(),
      };

      logger.info(`Member notification sent for claim ${claimId}`, {
        claimId,
      });
    } catch (error) {
      memberAction.status = 'failed';
      memberAction.error = error instanceof Error ? error.message : 'Unknown error';
    }

    actions.push(memberAction);

    // Provider notification (if appropriate)
    if (riskLevel === 'critical') {
      const providerAction: AutomatedAction = {
        id: `action_${claimId}_notify_provider`,
        claimId,
        actionType: 'provider_notification',
        status: 'pending',
        reason: `Notifying provider of fraud investigation`,
        metadata: {
          notificationType: 'fraud_investigation_provider',
          riskLevel,
        },
        createdAt: new Date().toISOString(),
      };

      try {
        // TODO: Call notification service for provider
        providerAction.status = 'completed';
        providerAction.completedAt = new Date().toISOString();

        logger.info(`Provider notification sent for claim ${claimId}`, {
          claimId,
        });
      } catch (error) {
        providerAction.status = 'failed';
        providerAction.error = error instanceof Error ? error.message : 'Unknown error';
      }

      actions.push(providerAction);
    }

    this.actions.set(memberAction.id, memberAction);
    return actions;
  }

  /**
   * Queue claim for manual review
   */
  private async queueForManualReview(
    claimId: number,
    riskScore: number,
    indicators: string[]
  ): Promise<AutomatedAction> {
    const action: AutomatedAction = {
      id: `action_${claimId}_manual_review`,
      claimId,
      actionType: 'auto_review',
      status: 'pending',
      reason: `Claim queued for manual review due to fraud risk score ${riskScore}`,
      metadata: {
        riskScore,
        indicators,
        reviewPriority: this.calculateReviewPriority(riskScore),
        reviewDeadlineHours: 24,
      },
      createdAt: new Date().toISOString(),
    };

    try {
      // TODO: Queue in claims management system
      // await claimsServiceClient.queueForReview(claimId, {
      //   reason: 'fraud_detection',
      //   priority: action.metadata.reviewPriority,
      // });

      action.status = 'completed';
      action.completedAt = new Date().toISOString();
      action.result = {
        queuedForReview: true,
        queuedDate: new Date().toISOString(),
        priority: action.metadata.reviewPriority,
      };

      logger.info(`Claim queued for manual review`, {
        claimId,
        riskScore,
        priority: action.metadata.reviewPriority,
      });
    } catch (error) {
      action.status = 'failed';
      action.error = error instanceof Error ? error.message : 'Unknown error';
    }

    this.actions.set(action.id, action);
    return action;
  }

  /**
   * Get action status
   */
  async getActionStatus(actionId: string): Promise<AutomatedAction | null> {
    return this.actions.get(actionId) || null;
  }

  /**
   * Get all actions for a claim
   */
  async getClaimActions(claimId: number): Promise<AutomatedAction[]> {
    return Array.from(this.actions.values()).filter(action => action.claimId === claimId);
  }

  /**
   * Calculate review priority based on risk score
   */
  private calculateReviewPriority(riskScore: number): 'low' | 'medium' | 'high' | 'urgent' {
    if (riskScore >= 80) return 'urgent';
    if (riskScore >= 60) return 'high';
    if (riskScore >= 40) return 'medium';
    return 'low';
  }

  /**
   * Retry failed action
   */
  async retryAction(actionId: string): Promise<AutomatedAction> {
    const action = this.actions.get(actionId);

    if (!action) {
      throw new Error(`Action ${actionId} not found`);
    }

    if (action.status !== 'failed') {
      throw new Error(`Cannot retry action with status ${action.status}`);
    }

    // Reset action and retry based on type
    logger.info(`Retrying action ${actionId}`, {
      claimId: action.claimId,
      actionType: action.actionType,
    });

    // Re-trigger the action
    switch (action.actionType) {
      case 'auto_deny':
        return await this.autoDenyClaim(
          action.claimId,
          action.metadata.riskLevel || 'critical',
          action.metadata.indicators || []
        );
      case 'initiate_recovery':
        return await this.initiateRecovery(action.claimId, action.metadata.riskScore || 75);
      default:
        throw new Error(`Cannot retry action type ${action.actionType}`);
    }
  }
}

// Export singleton instance
export const automatedActionsService = new AutomatedActionsService();
